export const FIND_BY_CITY = 'FIND_BY_CITY';
export const FIND_BY_CITY_SUCCESS = 'FIND_BY_CITY_SUCCESS';
export const FIND_BY_CITY_FAILURE = 'FIND_BY_CITY_FAILURE';
export const FIND_FORECAST = 'FIND_FORECAST';
export const FIND_FORECAST_SUCCESS = 'FIND_FORECAST_SUCCESS';
export const FIND_FORECAST_FAILURE = 'FIND_FORECAST_FAILURE';